export const KAFKA_TOPICS = {
  LOG_ACTION: "log.action",
  NOTIFY_EVENT: "notify.event",

  ASSET_CREATED: "asset.created",
  ASSET_UPDATED: "asset.updated",
  ASSET_TRANSFER: "asset.transfer",
  ASSET_DELETED: "asset.deleted",
  ASSET_RESTORED: "asset.restored",

  // Vehicle related events
  VEHICLE_TASK_DUE_SOON: "vehicle.task.due_soon",
  VEHICLE_TASK_OVERDUE: "vehicle.task.overdue",
  VEHICLE_TASK_COMPLETED: "vehicle.task.completed",
  VEHICLE_TASK_CREATED: "vehicle.task.created",
  VEHICLE_TASK_UPDATED: "vehicle.task.updated",
  VEHICLE_TASK_DELETED: "vehicle.task.deleted",
  VEHICLE_TASK_NEXT_PLANNED: "vehicle.task.next_planned",

  VEHICLE_DOCUMENT_CREATED: "vehicle.document.created",
  VEHICLE_DOCUMENT_UPDATED: "vehicle.document.updated",
  VEHICLE_DOCUMENT_DELETED: "vehicle.document.deleted",
  VEHICLE_DOCUMENT_DUE_SOON: "vehicle.document.due_soon",
  VEHICLE_DOCUMENT_RENEWED: "vehicle.document.renewed",
  VEHICLE_DOCUMENT_EXPIRING: "vehicle.document.expiring",

  VEHICLE_CREATED: "vehicle.created",
  VEHICLE_UPDATED: "vehicle.updated",
  VEHICLE_DELETED: "vehicle.deleted",
  VEHICLE_MILEAGE_UPDATED: "vehicle.mileage.updated",

  VEHICLE_TASK_TEMPLATE_CREATED: "vehicle.task_template.created",
  VEHICLE_TASK_TEMPLATE_UPDATED: "vehicle.task_template.updated",
  VEHICLE_TASK_TEMPLATE_ACTIVATED: "vehicle.task_template.activated",
  VEHICLE_TASK_TEMPLATE_DEACTIVATED: "vehicle.task_template.deactivated",

  USER_CREATED: "user.created",
  USER_UPDATED: "user.updated",
  USER_DELETED: "user.deleted",

  STOCK_LOW: "stock.low",
  STOCK_CRITICAL: "stock.critical",
  STOCK_REPLENISHED: "stock.replenished",

  AUTH_OTP_REQUESTED: "auth.otp.requested",
} as const;

export type EventKey = typeof KAFKA_TOPICS;

export const TOPICS: Record<string, string> = {
  [KAFKA_TOPICS.ASSET_CREATED]: KAFKA_TOPICS.ASSET_CREATED,
  [KAFKA_TOPICS.ASSET_UPDATED]: KAFKA_TOPICS.ASSET_UPDATED,
  [KAFKA_TOPICS.ASSET_TRANSFER]: KAFKA_TOPICS.ASSET_TRANSFER,
  [KAFKA_TOPICS.ASSET_DELETED]: KAFKA_TOPICS.ASSET_DELETED,
  [KAFKA_TOPICS.ASSET_RESTORED]: KAFKA_TOPICS.ASSET_RESTORED,

  [KAFKA_TOPICS.VEHICLE_TASK_DUE_SOON]: KAFKA_TOPICS.VEHICLE_TASK_DUE_SOON,
  [KAFKA_TOPICS.VEHICLE_TASK_OVERDUE]: KAFKA_TOPICS.VEHICLE_TASK_OVERDUE,
  [KAFKA_TOPICS.VEHICLE_TASK_COMPLETED]: KAFKA_TOPICS.VEHICLE_TASK_COMPLETED,
  [KAFKA_TOPICS.VEHICLE_TASK_CREATED]: KAFKA_TOPICS.VEHICLE_TASK_CREATED,
  [KAFKA_TOPICS.VEHICLE_TASK_UPDATED]: KAFKA_TOPICS.VEHICLE_TASK_UPDATED,
  [KAFKA_TOPICS.VEHICLE_TASK_DELETED]: KAFKA_TOPICS.VEHICLE_TASK_DELETED,
  [KAFKA_TOPICS.VEHICLE_TASK_NEXT_PLANNED]: KAFKA_TOPICS.VEHICLE_TASK_NEXT_PLANNED,

  [KAFKA_TOPICS.VEHICLE_DOCUMENT_CREATED]: KAFKA_TOPICS.VEHICLE_DOCUMENT_CREATED,
  [KAFKA_TOPICS.VEHICLE_DOCUMENT_UPDATED]: KAFKA_TOPICS.VEHICLE_DOCUMENT_UPDATED,
  [KAFKA_TOPICS.VEHICLE_DOCUMENT_DELETED]: KAFKA_TOPICS.VEHICLE_DOCUMENT_DELETED,
  [KAFKA_TOPICS.VEHICLE_DOCUMENT_EXPIRING]: KAFKA_TOPICS.VEHICLE_DOCUMENT_EXPIRING,
  [KAFKA_TOPICS.VEHICLE_DOCUMENT_DUE_SOON]: KAFKA_TOPICS.VEHICLE_DOCUMENT_DUE_SOON,
  [KAFKA_TOPICS.VEHICLE_DOCUMENT_RENEWED]: KAFKA_TOPICS.VEHICLE_DOCUMENT_RENEWED,

  [KAFKA_TOPICS.VEHICLE_CREATED]: KAFKA_TOPICS.VEHICLE_CREATED,
  [KAFKA_TOPICS.VEHICLE_UPDATED]: KAFKA_TOPICS.VEHICLE_UPDATED,
  [KAFKA_TOPICS.VEHICLE_DELETED]: KAFKA_TOPICS.VEHICLE_DELETED,
  [KAFKA_TOPICS.VEHICLE_MILEAGE_UPDATED]: KAFKA_TOPICS.VEHICLE_MILEAGE_UPDATED,

  [KAFKA_TOPICS.USER_CREATED]: KAFKA_TOPICS.USER_CREATED,
  [KAFKA_TOPICS.USER_UPDATED]: KAFKA_TOPICS.USER_UPDATED,
  [KAFKA_TOPICS.USER_DELETED]: KAFKA_TOPICS.USER_DELETED,

  [KAFKA_TOPICS.VEHICLE_TASK_TEMPLATE_CREATED]: KAFKA_TOPICS.VEHICLE_TASK_TEMPLATE_CREATED,
  [KAFKA_TOPICS.VEHICLE_TASK_TEMPLATE_UPDATED]: KAFKA_TOPICS.VEHICLE_TASK_TEMPLATE_UPDATED,
  [KAFKA_TOPICS.VEHICLE_TASK_TEMPLATE_ACTIVATED]: KAFKA_TOPICS.VEHICLE_TASK_TEMPLATE_ACTIVATED,
  [KAFKA_TOPICS.VEHICLE_TASK_TEMPLATE_DEACTIVATED]: KAFKA_TOPICS.VEHICLE_TASK_TEMPLATE_DEACTIVATED,

  [KAFKA_TOPICS.STOCK_LOW]: KAFKA_TOPICS.STOCK_LOW,
  [KAFKA_TOPICS.STOCK_CRITICAL]: KAFKA_TOPICS.STOCK_CRITICAL,
  [KAFKA_TOPICS.STOCK_REPLENISHED]: KAFKA_TOPICS.STOCK_REPLENISHED,

  [KAFKA_TOPICS.LOG_ACTION]: KAFKA_TOPICS.LOG_ACTION,
  [KAFKA_TOPICS.NOTIFY_EVENT]: KAFKA_TOPICS.NOTIFY_EVENT,

  [KAFKA_TOPICS.AUTH_OTP_REQUESTED]: KAFKA_TOPICS.AUTH_OTP_REQUESTED,
};
