enum AppErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_USER_AGENT = "INVALID_USER_AGENT",
  INVALID_SESSION = "INVALID_SESSION",
  INVALID_VERIFICATION_CODE_TYPE = "INVALID_VERIFICATION_CODE_TYPE",
  INVALID_VERIFICATION_CODE_EXPIRED = "INVALID_VERIFICATION_CODE_EXPIRED",
  INVALID_VERIFICATION_CODE_USED = "INVALID_VERIFICATION_CODE_USED",
  INVALID_VERIFICATION_CODE_NOT_FOUND = "INVALID_VERIFICATION_CODE_NOT_FOUND",
  INVALID_VERIFICATION_CODE_NOT_EXPIRED = "INVALID_VERIFICATION_CODE_NOT_EXPIRED",
  INVALID_VERIFICATION_CODE_NOT_USED = "INVALID_VERIFICATION_CODE_NOT_USED",
  MONGO_ERROR = "MONGO_ERROR",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
}

export default AppErrorCode;
