export const OK = 200;
export const CREATED = 201;
export const BAD_REQUEST = 400;
export const UNAUTHORIZED = 401;
export const FORBIDDEN = 403;
export const NOT_FOUND = 404;
export const CONFLICT = 409;
export const UNPROCESSABLE_CONTENT = 422;
export const TOO_MANY_REQUESTS = 429;
export const INTERNAL_SERVER_ERROR = 500;

export type HttpStatusCode =
  | typeof OK
  | typeof CREATED
  | typeof BAD_REQUEST
  | typeof UNAUTHORIZED
  | typeof FORBIDDEN
  | typeof NOT_FOUND
  | typeof CONFLICT
  | typeof UNPROCESSABLE_CONTENT
  | typeof TOO_MANY_REQUESTS
  | typeof INTERNAL_SERVER_ERROR;

enum AppErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_USER_AGENT = "INVALID_USER_AGENT",
  INVALID_SESSION = "INVALID_SESSION",
  INVALID_VERIFICATION_CODE_TYPE = "INVALID_VERIFICATION_CODE_TYPE",
  INVALID_VERIFICATION_CODE_EXPIRED = "INVALID_VERIFICATION_CODE_EXPIRED",
  INVALID_VERIFICATION_CODE_USED = "INVALID_VERIFICATION_CODE_USED",
  INVALID_VERIFICATION_CODE_NOT_FOUND = "INVALID_VERIFICATION_CODE_NOT_FOUND",
  INVALID_VERIFICATION_CODE_NOT_EXPIRED = "INVALID_VERIFICATION_CODE_NOT_EXPIRED",
  INVALID_VERIFICATION_CODE_NOT_USED = "INVALID_VERIFICATION_CODE_NOT_USED",
  MONGO_ERROR = "MONGO_ERROR",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
}

export default AppErrorCode;
