import mongoose, { FilterQuery, Types } from "mongoose";
import { Asset } from "../models/asset.model";
import { Category } from "../models/category.model";
import { Location } from "../models/location.model";
import { ensureSubcategoryUnderFamily } from "../utils/helpers";
import { response } from "@sigem/shared";
import { buildAssetCode } from "./code.service";
import { upsertAssetRefs } from "src/client/reference.client";

export type CreateAssetDTO = {
  code?: string; // unique + auto generated
  label: string;
  categoryId: string; // ref Category (sous-cat)
  locationId: string; // ref Location
  serialNumber?: string;
  brand?: string;
  model?: string;
  quantity?: number;
  unit?: string;
  situation?: "NEUF" | "EN_SERVICE" | "EN_PANNE" | "HORS_SERVICE" | "REFORME";
  observation?: string;
  notes?: string;
  attributes?: Record<string, any>;
};

export type UpdateAssetDTO = Partial<CreateAssetDTO>;

export class AssetService {
  static async list(q?: {
    search?: string;
    categoryId?: string;
    locationId?: string;
    situation?: CreateAssetDTO["situation"];
    page?: number;
    limit?: number;

    includeDeleted?: boolean;
  }) {
    const {
      search,
      categoryId,
      locationId,
      situation,
      page = 1,
      limit = 20,

      includeDeleted = false,
    } = q || {};
    const filter: FilterQuery<any> = {};

    // ✅ filtre soft-delete
    if (!includeDeleted) {
      filter.isDeleted = false;
    }

    if (categoryId) filter.categoryId = new Types.ObjectId(categoryId);
    if (locationId) filter.locationId = new Types.ObjectId(locationId);
    if (situation) filter.situation = situation;
    if (search) {
      const re = new RegExp(search, "i");
      filter.$or = [
        { code: re },
        { label: re },
        { brand: re },
        { model: re },
        { serialNumber: re },
      ];
    }

    const cursor = await Asset.find(filter)
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit)
      .populate("categoryId", "code label family canonicalPrefix")
      .populate(
        "locationId",
        "code path localisation batiment direction bureau"
      );

    const [items, total] = await Promise.all([
      cursor,
      Asset.countDocuments(filter),
    ]);
    if (!items) {
      response(null, "NOT_FOUND", "Assets not found", false, 404);
    }
    return response(
      { items, total, page, limit },
      null,
      "Assets fetched",
      true,
      200
    );
  }

  static async getById(id: string) {
    const asset = await Asset.findById(id)
      .populate("categoryId", "code label family canonicalPrefix")
      .populate(
        "locationId",
        "code path localisation batiment direction bureau"
      );
    if (!asset) {
      return response(null, "NOT_FOUND", "Asset not found", false, 404);
    }

    return response(asset, null, "Asset fetched", true, 200);
  }

  /**
   * Create asset in a Mongo transaction.
   * - Upsert sub-category when categoryId points a root family
   * - Validate location
   * - Asset `code` auto-generated by pre('validate') hook (no duplication here)
   */
  static async create(payload: CreateAssetDTO) {
    const session = await mongoose.startSession();

    // console.log(payload);

    try {
      return await session.withTransaction(async () => {
        // Normalisations
        if (payload.code) payload.code = payload.code.trim().toUpperCase();
        payload.label = payload.label.trim();

        const dept = (payload as any).dept || "MG";

        // 1) Charger la catégorie fournie
        const cat = await Category.findById(payload.categoryId)
          .select("parentId label family canonicalPrefix")
          .session(session);
        if (!cat) {
          throw new Error("Category not found");
        }

        // 2) If family node, ensure sub-cat (sub-cat label == asset label)
        if (!cat.parentId) {
          const sub = await ensureSubcategoryUnderFamily(
            session,
            String(cat._id),
            payload.label
          );

          payload.categoryId = String(sub!._id);
        }

        // 3) Validate location, qty
        const locExists = await Location.exists({
          _id: payload.locationId,
        }).session(session);
        if (!locExists) throw new Error("Location not found");
        if (payload.quantity !== undefined && payload.quantity < 0) {
          throw new Error("Quantity cannot be negative");
        }

        // 4) Create asset (hooks generate code)
        const doc = new Asset(payload);
        const created = await doc.save({ session });

        // ✅ Upsert dictionary AFTER successful save (outside Mongo transaction scope)
        // Still executed here, but only after DB op succeeded.
        // (If transaction later fails, this could still run; if you want perfect consistency,
        //  we can move it after withTransaction returns.)


        await upsertAssetRefs({
          dept,
          label: created.label,
          brand: created.brand,
          model: created.model,
        });

        return created;
      });
    } finally {
      session.endSession();
    }
  }

  static async getRawById(id: string) {
    return Asset.findById(id).select("label code locationId situation quantity").lean();
  }

  /**
   * Update in transaction. We DO NOT recompute code automatically.
   * If the business wants a recode on category/location change, do a dedicated endpoint.
   */
  static async update(
    id: string,
    payload: UpdateAssetDTO & { forceRegenerateCode?: boolean }
  ) {
    const session = await mongoose.startSession();
    try {
      return await session.withTransaction(async () => {
        // Load existing
        const existing = await Asset.findById(id).session(session);
        if (!existing) throw new Error("Asset not found");

        const dept = (existing as any).dept ?? "MG";

        // Normalisations
        if (payload.label) payload.label = payload.label.trim();
        if (payload.code) delete payload.code; // l’utilisateur ne peut pas forcer un code manuel
        delete (payload as any).prefix;
        delete (payload as any).sequence;

        // Vars finales pour la régénération
        let finalCategoryId = String(existing.categoryId);
        let finalLocationId = String(existing.locationId);
        let finalLabel = existing.label;

        if (payload.categoryId) {
          const newCat = await Category.findById(payload.categoryId)
            .select("parentId label family canonicalPrefix")
            .session(session);
          if (!newCat) throw new Error("Category not found");

          // Si on passe une famille root → il faut créer/assurer une sous-cat automatique
          if (!newCat.parentId) {
            const sub = await ensureSubcategoryUnderFamily(
              session,
              String(newCat._id),
              payload.label ?? existing.label
            );

            payload.categoryId = String(sub!._id);
            // finalCategoryId = String(sub!._id);
          }
          finalCategoryId = String(payload.categoryId);
        }

        // --- LOCATION LOGIC ---
        if (payload.locationId) {
          const locOk = await Location.exists({
            _id: payload.locationId,
          }).session(session);
          if (!locOk) throw new Error("Location not found");
          finalLocationId = String(payload.locationId);
        }

        // --- LABEL LOGIC ---
        if (payload.label) {
          finalLabel = payload.label;
        }

        // Garder la validation de quantité
        if (payload.quantity !== undefined && payload.quantity < 0) {
          throw new Error("Quantity cannot be negative");
        }

        // --- SHOULD WE REGENERATE CODE ? ---
        const prevCategoryId = String(existing.categoryId);
        const prevLocationId = String(existing.locationId);
        const prevLabel = existing.label;

        const categoryChanged = finalCategoryId !== prevCategoryId;
        const locationChanged = finalLocationId !== prevLocationId;
        const labelChanged = finalLabel !== prevLabel;

        const shouldRecode = Boolean(
          payload.forceRegenerateCode ?? (categoryChanged || locationChanged || labelChanged)
        );

        if (shouldRecode) {
          const { code, prefix, sequence } = await buildAssetCode(
            finalCategoryId,
            finalLocationId,
            undefined,
            finalLabel,
            session
          );

          payload.code = code;
          (payload as any).prefix = prefix;
          (payload as any).sequence = sequence;
        }

        // --- APPLY UPDATE ---
        Object.assign(existing, payload);
        const saved = await existing.save({ session });

        if (saved) {
          await upsertAssetRefs({
            dept,
            label: payload.label !== undefined ? payload.label : null,
            brand: payload.brand !== undefined ? payload.brand : null,
            model: payload.model !== undefined ? payload.model : null,
          });
        }

        return saved;

      });
    } finally {
      session.endSession();
    }
  }

  static async remove(id: string) {
    const session = await mongoose.startSession();

    try {
      return await session.withTransaction(async () => {
        // Mark asset as deleted
        const updated = await Asset.findByIdAndUpdate(
          id,
          {
            isDeleted: true,
            isRestored: false,
          },
          { new: true, session }
        );

        return updated;
      });
    } finally {
      session.endSession();
    }
  }

  static async restore(id: string) {
    const session = await mongoose.startSession();

    try {
      return await session.withTransaction(async () => {
        const updated = await Asset.findByIdAndUpdate(
          id,
          {
            isDeleted: false,
            isRestored: true,
          },
          { new: true, session }
        );

        return updated;
      });
    } finally {
      session.endSession();
    }
  }

  // (Optionnel) utile si tu veux protéger delete location si assets présents
  static async countByLocation(locationId: string) {
    return Asset.countDocuments({ locationId });
  }
}